pipeline {
    agent any

    environment {
        APP_NAME = 'dms-server'
        
        BUILD_TARGET = 'dev'
        BUILD_VERSION = "1.0.${env.BUILD_ID}-${env.BUILD_TARGET}"

        DEPLOY_CREDENTIALS_ID = 'github-user'
        DEPLOY_REPO_URL = 'github.com/dnjsakf/argocd-apps.git'
        DEPLOY_PATH = "${env.APP_NAME}/${env.APP_NAME}-deployment.yaml"

        DOCKER_CREDENTIALS_ID = 'docker-user'
        DOCKER_IMAGE_NAME = "dnjsakf/${env.APP_NAME}"
        DOCKER_IMAGE_TAG = "${env.DOCKER_IMAGE_NAME}:${env.BUILD_VERSION}"
        DOCKER_IMAGE_TAG_LATEST = "${env.DOCKER_IMAGE_NAME}:latest"

        ARGOCD_SERVER = 'https://host.docker.internal:38080'
        ARGOCD_AUTH_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhcGl1c2VyOmFwaUtleSIsIm5iZiI6MTcyODAyMDM1OCwiaWF0IjoxNzI4MDIwMzU4LCJqdGkiOiI1NjIzODM5Yy0yY2VmLTQzMzktYjc5NS02OGM5OTJiOTJhNjcifQ.XLd48Zyd1bU14SpFDnGZrJlf5t4ua3rqKHBHJAo6n3k'
    }

    stages {
        stage('Build') {
            steps {
                echo "Express is no build"
            }
        }

        stage('Stop Container & Remove Image') {
            steps {
                script {
                    sh """
                    if [ \$(docker ps -a -q -f name=\"${env.APP_NAME}\") ]; then
                        docker stop ${env.APP_NAME}
                        docker rm ${env.APP_NAME}
                    fi
                    """
                    sh """
                    IMAGE_ID=\$(docker images -q -f reference=${env.DOCKER_IMAGE_TAG_LATEST})
                    if [ -n "\$IMAGE_ID" ]; then
                        echo "Docker Image Clean...  ${env.DOCKER_IMAGE_TAG_LATEST}"
                        docker rmi ${env.DOCKER_IMAGE_TAG_LATEST}
                    fi
                    """
                }
            }
        }

        stage('Docker Image Build & Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${env.DOCKER_CREDENTIALS_ID}") {
                        def buildImage = docker.build("${env.DOCKER_IMAGE_TAG}", "-f ./cicd/${env.BUILD_TARGET}/Dockerfile .")
                        buildImage.push()

                        sh "docker tag ${env.DOCKER_IMAGE_TAG} ${env.DOCKER_IMAGE_TAG_LATEST}"
                        sh "docker push ${env.DOCKER_IMAGE_TAG_LATEST}"
                    }
                }
            }
        }

        // stage('Trigger ArgoCD Sync') {
        stage('Running container') {
            steps {
                script {
                    def container = docker.image("${env.DOCKER_IMAGE_TAG_LATEST}")
                    // container.run("-d -p 3000:80 --network bridge --name ${env.APP_NAME}")
                    container.run("-d --network bridge --name ${env.APP_NAME}")
                }
            }
        }
    }

    post {
        always {
            cleanWs()

            script {
                sh """
                IMAGE_ID=\$(docker images -q -f reference=${env.DOCKER_IMAGE_TAG})
                if [ -n "\$IMAGE_ID" ]; then
                    echo "Docker Image Clean...  ${env.DOCKER_IMAGE_TAG}"
                    docker rmi ${env.DOCKER_IMAGE_TAG}
                fi
                """
            }
        }
        success {
            sh 'echo "This will run only if all stages succeed"'
        }
        failure {
            sh 'echo "This will run only if any stage fails"'
        }
    }
}
